better script flow controls

diff --git a/scripts/create-user-accounts b/scripts/create-user-accounts
--- a/scripts/create-user-accounts
+++ b/scripts/create-user-accounts
@@ -46,8 +46,19 @@ create_user_accounts() {
   fi
 }
 
+echo "Creating Sensu user accounts..."
 wait-for-sensuctl
-check_deps
-validate_io
-validate_api_url
+if [ $? -gt 0 ]; then
+  echo "Failed to create Sensu user accounts."
+  exit 2
+fi
+check_deps && \
+validate_io && \
+validate_api_url && \
 create_user_accounts
+if [ $? -gt 0 ]; then
+  echo "Failed to create Sensu user accounts."
+  exit 2
+fi
+echo ""
+exit 0
