swap out rocketchat for mattermost!!

diff --git a/scripts/seed-workshop-resources b/scripts/seed-workshop-resources
--- a/scripts/seed-workshop-resources
+++ b/scripts/seed-workshop-resources
@@ -114,11 +114,26 @@ initialize_workshop_chat() {
     echo "Failed to initialize Mattermost via bulk import."
     echo ""
     exit 2
-  else 
+  else
     echo "Successfully initialized Mattermost service!"
     echo ""
-    exit 0
   fi
+}
+
+seed_workshop_chat() {
+  echo "Seeding Mattermost service..."
+  mmctl auth login http://mattermost:8065 --name sensu-workshop --username sensu --password workshop > /dev/null 2>&1
+  export MATTERMOST_WEBHOOK_URL="http://mattermost:8065/hooks/$(mmctl webhook create-incoming --channel workshop:alerts --user sensu --format json | jq -r .id)"
+  echo "{\"webhook_url\": \"${MATTERMOST_WEBHOOK_URL}\", \"ttl\": \"30s\"}" | jq . > ${VAULT_WORKSHOP_SEEDS}/mattermost.json
+  if [ $? -gt 0 ]; then
+    echo "Failed to create a Mattermost incoming webhook."
+    echo ""
+    exit 2
+  else
+    echo "Successfully created a Mattermost incoming webhook!"
+    echo ""
+  fi
+  # TODO: add a for-loop to add Mattermost users for instructor-led workshop
 }
 
 seed_user_envrc_files() {
@@ -158,6 +173,7 @@ seed_cluster && \
 seed_namespaces && \
 seed_user_envrc_files && \
 initialize_workshop_chat && \
+seed_workshop_chat && \
 seed_secrets
 if [ $? -gt 0 ]; then
   echo "Failed to create Sensu user accounts."
