initial commit of postgres automation

diff --git a/scripts/seed-workshop-resources b/scripts/seed-workshop-resources
--- a/scripts/seed-workshop-resources
+++ b/scripts/seed-workshop-resources
@@ -3,6 +3,7 @@
 SENSU_API_URL=${SENSU_API_URL:-"http://sensu-backend:8080"}
 SENSU_NAMESPACE=${SENSU_NAMESPACE:-"default"}
 SENSU_CLUSTER_CONFIG=${SENSU_CLUSTER_CONFIG:-"config/sensu/cluster"}
+SENSU_CLUSTER_EXTRAS=${SENSU_CLUSTER_EXTRAS:-"config/sensu/extras"}
 SENSU_WORKSHOP_SEEDS=${SENSU_WORKSHOP_SEEDS:-"config/sensu/seeds"}
 USERS_JSON=${USERS_JSON:-"users/users.json"}
 SENSU_WORKSHOP_ENVRC_TEMPLATE=${SENSU_WORKSHOP_ENVRC_TEMPLATE:-"users/user.envrc.template"}
@@ -56,8 +57,24 @@ seed_cluster() {
   echo "Applying cluster configuration from ${SENSU_CLUSTER_CONFIG}"
   /usr/local/bin/sensuctl create -r -f ${SENSU_CLUSTER_CONFIG}
   if [ $? -ne 0 ]; then
-    echo "Error encountered while seeding workshop user namespaces"
+    echo "Error encountered while seeding workshop cluster configuration"
     exit 2
+  fi
+}
+
+seed_extras() {
+  if [ ! -z ${SENSU_CLUSTER_EXTRAS} ]; then
+    if [ ! -d ${SENSU_CLUSTER_EXTRAS} ]; then
+      echo "Missing or invalid cluster extras: \"${SENSU_CLUSTER_EXTRAS}\" (must be a directory)"
+      exit 2
+    else
+      echo "Applying extra configuration from ${SENSU_CLUSTER_EXTRAS}"
+      /usr/local/bin/sensuctl create -r -f ${SENSU_CLUSTER_EXTRAS}
+      if [ $? -ne 0 ]; then
+        echo "Error encountered while seeding workshop cluster extras"
+        exit 2
+      fi
+    fi
   fi
 }
 
@@ -110,6 +127,7 @@ check_deps && \
 validate_io && \
 validate_api_urls && \
 seed_cluster && \
+seed_extras && \
 seed_namespaces && \
 seed_user_envrc_files && \
 seed_secrets
