refactor seeding so downstream federated clusters start with minimum viable seeds

diff --git a/scripts/seed-workshop-resources b/scripts/seed-workshop-resources
--- a/scripts/seed-workshop-resources
+++ b/scripts/seed-workshop-resources
@@ -77,28 +77,30 @@ seed_cluster_extras() {
 }
 
 seed_users() {
-  echo "Seeding workshop users, namespaces, and RBAC profiles..."
-  wait-for ${SENSU_API_URL}/health
-  for USER in $( cat "${USERS_JSON}" | jq -r '.[] | @base64' | sort -u); do
-    export USERNAME_ORIGINAL=$(echo ${USER} | base64 -d | jq -r .username)
-    export USERNAME=$(echo ${USERNAME_ORIGINAL} | awk -F "@" '{print $1}')
-    export PASSWORD=$(echo ${USER} | base64 -d | jq -r .password)
-    if [ ${PASSWORD} == "null" ]; then
-      export PASSWORD="${WORKSHOP_DEFAULT_TRAINEE_PASSWORD}"
-    fi
-    export PASSWORD_HASH=$(echo ${USER} | base64 -d | jq -r .password_hash)
-    if [ ${PASSWORD_HASH} == "null" ]; then
-      export PASSWORD_HASH=$(sensuctl user hash-password ${PASSWORD} 2> /dev/null)
-    fi
-    if [ -z ${PASSWORD_HASH} ]; then
-      echo "Failed to generate password hash for user ${USERNAME}; skipping..."
-    else
-      echo "Generating user profile for user: ${USERNAME}"
-      cat ${USER_TEMPLATE} | envsubst | /usr/local/bin/sensuctl --api-url ${SENSU_API_URL} --api-key ${SENSU_API_KEY} create
-    fi
-  done
-  echo "Successfully generated Sensu RBAC templates!"
-  echo ""
+  if [ -z ${SKIP_SEED_USERS} ]; then
+    echo "Seeding workshop users, namespaces, and RBAC profiles..."
+    wait-for ${SENSU_API_URL}/health
+    for USER in $( cat "${USERS_JSON}" | jq -r '.[] | @base64' | sort -u); do
+      export USERNAME_ORIGINAL=$(echo ${USER} | base64 -d | jq -r .username)
+      export USERNAME=$(echo ${USERNAME_ORIGINAL} | awk -F "@" '{print $1}')
+      export PASSWORD=$(echo ${USER} | base64 -d | jq -r .password)
+      if [ ${PASSWORD} == "null" ]; then
+        export PASSWORD="${WORKSHOP_DEFAULT_TRAINEE_PASSWORD}"
+      fi
+      export PASSWORD_HASH=$(echo ${USER} | base64 -d | jq -r .password_hash)
+      if [ ${PASSWORD_HASH} == "null" ]; then
+        export PASSWORD_HASH=$(sensuctl user hash-password ${PASSWORD} 2> /dev/null)
+      fi
+      if [ -z ${PASSWORD_HASH} ]; then
+        echo "Failed to generate password hash for user ${USERNAME}; skipping..."
+      else
+        echo "Generating user profile for user: ${USERNAME}"
+        cat ${USER_TEMPLATE} | envsubst | /usr/local/bin/sensuctl --api-url ${SENSU_API_URL} --api-key ${SENSU_API_KEY} create
+      fi
+    done
+    echo "Successfully generated Sensu RBAC templates!"
+    echo ""
+  fi  
 }
 
 seed_namespaces() {
@@ -125,101 +127,118 @@ seed_namespaces() {
 }
 
 initialize_workshop_chat() {
-  echo "Initializing Mattermost service..."
-  wait-for mattermost:8065
-  # Generate the Mattermost bulk import file (JSONL)
-  cat config/mattermost/data.jsonl.template | envsubst | tee config/mattermost/data.jsonl > /dev/null 2>&1
-  # Copy the Mattermost bulk import file to the Mattermost service container
-  docker cp config/mattermost/data.jsonl workshop_mattermost_1:/mattermost/data/data.jsonl
-  # Perform the Mattermost bulk import
-  docker-compose exec -T mattermost /mattermost/bin/mattermost import bulk /mattermost/data/data.jsonl --apply > /dev/null 2>&1
-  if [ $? -gt 0 ]; then
-    echo "Failed to initialize Mattermost via bulk import."
-    echo ""
-    exit 2
-  else
-    echo "Successfully initialized Mattermost service!"
-    echo ""
-  fi
+  if [ -z ${SKIP_SEED_CHAT} ]; then
+    echo "Initializing Mattermost service..."
+    wait-for mattermost:8065
+    # Generate the Mattermost bulk import file (JSONL)
+    cat config/mattermost/data.jsonl.template | envsubst | tee config/mattermost/data.jsonl > /dev/null 2>&1
+    # Copy the Mattermost bulk import file to the Mattermost service container
+    docker cp config/mattermost/data.jsonl workshop_mattermost_1:/mattermost/data/data.jsonl
+    # Perform the Mattermost bulk import
+    docker-compose exec -T mattermost /mattermost/bin/mattermost import bulk /mattermost/data/data.jsonl --apply > /dev/null 2>&1
+    if [ $? -gt 0 ]; then
+      echo "Failed to initialize Mattermost via bulk import."
+      echo ""
+      exit 2
+    else
+      echo "Successfully initialized Mattermost service!"
+      echo ""
+    fi
+  fi 
 }
 
 seed_workshop_chat() {
-  echo "Seeding Mattermost service..."
-  # Configure Mattermost CLI (mmctl)
-  mmctl auth login http://mattermost:8065 --name sensu-workshop --username ${MATTERMOST_ADMIN_USER} --password ${MATTERMOST_ADMIN_PASSWORD} > /dev/null 2>&1
-  # Generate a Mattermost webhook URL via mmctl
-  export MATTERMOST_WEBHOOK_URL="http://mattermost:8065/hooks/$(mmctl webhook create-incoming --channel workshop:alerts --user ${MATTERMOST_ADMIN_USER} --format json | jq -r .id)"
-  # Generate a Vault secret JSON file to seed Vault
-  echo "{\"webhook_url\": \"${MATTERMOST_WEBHOOK_URL}\", \"channel\": \"#alerts\", \"ttl\": \"30s\"}" | jq . > ${VAULT_WORKSHOP_SEEDS}/mattermost.json
-  if [ $? -gt 0 ]; then
-    echo "Failed to create a Mattermost incoming webhook."
-    echo ""
-    exit 2
-  else
-    echo "Successfully created a Mattermost incoming webhook!"
-    echo ""
+  if [ -z ${SKIP_SEED_CHAT} ]; then
+  	
+    echo "Seeding Mattermost service..."
+    # Configure Mattermost CLI (mmctl)
+    mmctl auth login http://mattermost:8065 --name sensu-workshop --username ${MATTERMOST_ADMIN_USER} --password ${MATTERMOST_ADMIN_PASSWORD} > /dev/null 2>&1
+    # Generate a Mattermost webhook URL via mmctl
+    export MATTERMOST_WEBHOOK_URL="http://mattermost:8065/hooks/$(mmctl webhook create-incoming --channel workshop:alerts --user ${MATTERMOST_ADMIN_USER} --format json | jq -r .id)"
+    # Generate a Vault secret JSON file to seed Vault
+    echo "{\"webhook_url\": \"${MATTERMOST_WEBHOOK_URL}\", \"channel\": \"#alerts\", \"ttl\": \"30s\"}" | jq . > ${VAULT_WORKSHOP_SEEDS}/mattermost.json
+    if [ $? -gt 0 ]; then
+      echo "Failed to create a Mattermost incoming webhook."
+      echo ""
+      exit 2
+    else
+      echo "Successfully created a Mattermost incoming webhook!"
+      echo ""
+    fi
+    # Turn off annoying popup notices
+    mmctl config set AnnouncementSettings.AdminNoticesEnabled false
+    mmctl config set AnnouncementSettings.UserNoticesEnabled false
   fi
-  # Turn off annoying popup notices
-  mmctl config set AnnouncementSettings.AdminNoticesEnabled false
-  mmctl config set AnnouncementSettings.UserNoticesEnabled false
 }
 
 seed_user_envrc_files() {
-  ERRORS=0
-  echo "Generating user environment files..."
-  for USER in $( cat "${USERS_JSON}" | jq -r '.[] | @base64' | sort -u); do
-    export USERNAME_ORIGINAL=$(echo ${USER} | base64 -d | jq -r .username)
-    export USERNAME=$(echo ${USERNAME_ORIGINAL} | awk -F "@" '{print $1}')
-    export PASSWORD=$(echo ${USER} | base64 -d | jq -r .password)
-    if [ -z ${PASSWORD} ]; then
-      export PASSWORD=${WORKSHOP_PASSWORD}
+  if [ -z ${SKIP_SEED_ENVRC} ]; then
+    ERRORS=0
+    echo "Generating user environment files..."
+    for USER in $( cat "${USERS_JSON}" | jq -r '.[] | @base64' | sort -u); do
+      export USERNAME_ORIGINAL=$(echo ${USER} | base64 -d | jq -r .username)
+      export USERNAME=$(echo ${USERNAME_ORIGINAL} | awk -F "@" '{print $1}')
+      export PASSWORD=$(echo ${USER} | base64 -d | jq -r .password)
+      if [ -z ${PASSWORD} ]; then
+        export PASSWORD=${WORKSHOP_PASSWORD}
+      fi
+      export USER_API_KEY=$(/usr/local/bin/sensuctl --api-url ${SENSU_API_URL} --api-key ${SENSU_API_KEY} api-key grant ${USERNAME} | awk -F "/" '{print $NF}')
+      echo "Generating user .envrc file: ${SENSU_WORKSHOP_USER_ENV_FILES}/${USERNAME}.envrc"
+      cat ${SENSU_WORKSHOP_ENVRC_TEMPLATE} | envsubst | tee ${SENSU_WORKSHOP_USER_ENV_FILES}/${USERNAME}.envrc > /dev/null 2>&1
+      ERRORS=$(expr ${ERRORS} + $?)
+      echo "Generating user .envrc.ps1 file: ${SENSU_WORKSHOP_USER_ENV_FILES}/${USERNAME}.envrc.ps1"
+      cat ${SENSU_WORKSHOP_PS1_TEMPLATE} | envsubst | tee ${SENSU_WORKSHOP_USER_ENV_FILES}/${USERNAME}.envrc.ps1 > /dev/null 2>&1
+      ERRORS=$(expr ${ERRORS} + $?)
+    done
+    if [ ${ERRORS} -ne 0 ]; then
+      echo "Error generating user environment files"
+      echo ""
+      exit 2
+    else
+      echo "Successfully generated user environment files!"
+      echo ""
     fi
-    export USER_API_KEY=$(/usr/local/bin/sensuctl --api-url ${SENSU_API_URL} --api-key ${SENSU_API_KEY} api-key grant ${USERNAME} | awk -F "/" '{print $NF}')
-    echo "Generating user .envrc file: ${SENSU_WORKSHOP_USER_ENV_FILES}/${USERNAME}.envrc"
-    cat ${SENSU_WORKSHOP_ENVRC_TEMPLATE} | envsubst | tee ${SENSU_WORKSHOP_USER_ENV_FILES}/${USERNAME}.envrc > /dev/null 2>&1
-    ERRORS=$(expr ${ERRORS} + $?)
-    echo "Generating user .envrc.ps1 file: ${SENSU_WORKSHOP_USER_ENV_FILES}/${USERNAME}.envrc.ps1"
-    cat ${SENSU_WORKSHOP_PS1_TEMPLATE} | envsubst | tee ${SENSU_WORKSHOP_USER_ENV_FILES}/${USERNAME}.envrc.ps1 > /dev/null 2>&1
-    ERRORS=$(expr ${ERRORS} + $?)
-  done
-  if [ ${ERRORS} -ne 0 ]; then
-    echo "Error generating user environment files"
-    echo ""
-    exit 2
-  else
-    echo "Successfully generated user environment files!"
-    echo ""
-  fi
+  fi  
 }
 
 seed_secrets() {
-  echo "Seeding Vault..."
-  wait-for ${VAULT_ADDR}/v1/sys/health
-  for SECRET in $(ls ${VAULT_WORKSHOP_SEEDS})
-  do
-    NAME=$(echo $SECRET | cut -d "." -f 1)
-    echo "Seeding Vault with secret key: ${VAULT_SECRET_PATH_PREFIX}/${NAME}"
-    vault kv put ${VAULT_SECRET_PATH_PREFIX}/${NAME} @${VAULT_WORKSHOP_SEEDS}/${SECRET} > /dev/null 2>&1
-    vault kv get --format json ${VAULT_SECRET_PATH_PREFIX}/${NAME} | jq .data.data
-  done
-  echo ""
+  if [ -z ${SKIP_SEED_SECRETS} ]; then
+    echo "Seeding Vault..."
+    wait-for ${VAULT_ADDR}/v1/sys/health
+    for SECRET in $(ls ${VAULT_WORKSHOP_SEEDS})
+    do
+      NAME=$(echo $SECRET | cut -d "." -f 1)
+      echo "Seeding Vault with secret key: ${VAULT_SECRET_PATH_PREFIX}/${NAME}"
+      vault kv put ${VAULT_SECRET_PATH_PREFIX}/${NAME} @${VAULT_WORKSHOP_SEEDS}/${SECRET} > /dev/null 2>&1
+      vault kv get --format json ${VAULT_SECRET_PATH_PREFIX}/${NAME} | jq .data.data
+    done
+    echo ""
+  fi
 }
 
 echo "Seeding Sensu Go Workshop resources for ${SENSU_API_URL}  ..."
 check_deps && \
 validate_io && \
 seed_cluster && \
-seed_cluster_extras && \
-seed_users && \
-seed_namespaces && \
-seed_user_envrc_files && \
-initialize_workshop_chat && \
-seed_workshop_chat && \
-seed_secrets
+seed_cluster_extras 
 if [ $? -gt 0 ]; then
   echo "Encountered an error while seeding workshop resources."
   echo ""
   exit 2
 fi
+
+if [ -z ${SKIP_FEDERATION_CLUSTER} ]; then
+  seed_users && \
+  seed_namespaces && \
+  seed_user_envrc_files && \
+  initialize_workshop_chat && \
+  seed_workshop_chat && \
+  seed_secrets
+  if [ $? -gt 0 ]; then
+    echo "Encountered an error while seeding workshop resources."
+    echo ""
+    exit 2
+  fi
+fi  
 echo ""
 exit 0
