new user env file generation! h/t @jspaleta

diff --git a/scripts/seed-workshop-resources b/scripts/seed-workshop-resources
--- a/scripts/seed-workshop-resources
+++ b/scripts/seed-workshop-resources
@@ -4,6 +4,10 @@ SENSU_API_URL=${SENSU_API_URL:-"http://sensu-backend:8080"}
 SENSU_NAMESPACE=${SENSU_NAMESPACE:-"default"}
 SENSU_CLUSTER_CONFIG=${SENSU_CLUSTER_CONFIG:-"config/sensu/cluster"}
 SENSU_WORKSHOP_SEEDS=${SENSU_WORKSHOP_SEEDS:-"config/sensu/seeds"}
+USERS_JSON=${USERS_JSON:-"users/users.json"}
+SENSU_WORKSHOP_ENVRC_TEMPLATE=${SENSU_WORKSHOP_ENVRC_TEMPLATE:-"users/user.envrc.template"}
+SENSU_WORKSHOP_PS1_TEMPLATE=${SENSU_WORKSHOP_PS1_TEMPLATE:-"users/user.envrc.ps1.template"}
+SENSU_WORKSHOP_USER_ENV_FILES=${SENSU_WORKSHOP_USER_ENV_FILES:-"/config"}
 VAULT_ADDR=${VAULT_ADDR:-"http://vault:8200"}
 VAULT_DEV_ROOT_TOKEN_ID=${VAULT_DEV_ROOT_TOKEN_ID:-"secretsmanager"}
 VAULT_SECRET_PATH_PREFIX=${VAULT_SECRET_PATH_PREFIX:-"secret/sensu"}
@@ -27,6 +31,10 @@ validate_io() {
   fi
   if [ ! -d ${SENSU_WORKSHOP_SEEDS} ]; then
     echo "Missing or invalid namespace seeding resources: \"${SENSU_WORKSHOP_SEEDS}\" (must be a directory)"
+    exit 2
+  fi
+  if [ ! -d ${SENSU_WORKSHOP_USER_ENV_FILES} ]; then
+    echo "Missing or invalid env file path: \"${SENSU_WORKSHOP_USER_ENV_FILES}\" (must be a directory)"
     exit 2
   fi
 }
@@ -65,6 +73,22 @@ seed_namespaces() {
   done
 }
 
+seed_user_envrc_files() {
+  for USER in $( cat "${USERS_JSON}" | jq -r '.[] | @base64' | sort -u); do
+    export USERNAME_ORIGINAL=$(echo ${USER} | base64 -d | jq -r .username)
+    export USERNAME=$(echo ${USERNAME_ORIGINAL} | awk -F "@" '{print $1}')
+    export PASSWORD=$(echo ${USER} | base64 -d | jq -r .password)
+    if [ -z ${PASSWORD} ]; then
+      export PASSWORD=${WORKSHOP_PASSWORD}
+    fi
+    export USER_API_KEY=$(sensuctl api-key grant ${USERNAME} | awk -F "/" '{print $NF}')
+    echo "Generating user .envrc file: ${SENSU_WORKSHOP_USER_ENV_FILES}/${USERNAME}.envrc"
+    cat ${SENSU_WORKSHOP_ENVRC_TEMPLATE} | envsubst | tee ${SENSU_WORKSHOP_USER_ENV_FILES}/${USERNAME}.envrc > /dev/null 2>&1
+    echo "Generating user .envrc.ps1 file: ${SENSU_WORKSHOP_USER_ENV_FILES}/${USERNAME}.envrc.ps1"
+    cat ${SENSU_WORKSHOP_PS1_TEMPLATE} | envsubst | tee ${SENSU_WORKSHOP_USER_ENV_FILES}/${USERNAME}.envrc.ps1 > /dev/null 2>&1
+  done
+}
+
 seed_secrets() {
   for SECRET in $(ls ${VAULT_WORKSHOP_SEEDS})
   do
@@ -81,4 +105,5 @@ validate_io
 validate_api_urls
 seed_cluster
 seed_namespaces
+seed_user_envrc_files
 seed_secrets
