bootstrap script refactor; upgrade to etcd 3.5.1

diff --git a/scripts/wait-for-sensu-backend b/scripts/wait-for-sensu-backend
--- a/scripts/wait-for-sensu-backend
+++ b/scripts/wait-for-sensu-backend
@@ -6,25 +6,26 @@ SENSU_BACKEND_CLUSTER_ADMIN_PASSWORD=${SENSU_BACKEND_CLUSTER_ADMIN_PASSWORD:-"se
 SENSU_BACKEND_CLUSTER_ADMIN_API_KEY=${SENSU_BACKEND_CLUSTER_ADMIN_API_KEY}
 SENSU_NAMESPACE=${SENSU_NAMESPACE:-"default"}
 SENSU_ETCD_CLIENT_URLS=${SENSU_ETCD_CLIENT_URLS}
-SENSU_INIT_TEMP_FILE="/root/.config/init"
+SENSU_INIT_TEMP_FILE="/root/.sensu-backend-init"
 INTERVAL=2
 RETRIES=5
 ATTEMPT=0
 SUCCESS=0
 
 sensu_backend_init() {
-  if [ ! -f ${SENSU_INIT_TEMP_FILE} ]; then
-    if [ ! -z ${SENSU_ETCD_CLIENT_URLS} ]; then
-      sensu-backend init --etcd-client-urls ${SENSU_ETCD_CLIENT_URLS} --cluster-admin-username ${SENSU_BACKEND_CLUSTER_ADMIN_USERNAME} --cluster-admin-password ${SENSU_BACKEND_CLUSTER_ADMIN_USERNAME} --cluster-admin-api-key ${SENSU_BACKEND_CLUSTER_ADMIN_API_KEY}
-      if [ $? -eq 0 ]; then
-        touch ${SENSU_INIT_TEMP_FILE}
-        return 0
-      fi
-      echo "Failed to initialize the Sensu backend"
+  echo "Initializing the Sensu backend..."
+  if [ ! -z ${SENSU_ETCD_CLIENT_URLS} ]; then
+    sensu-backend init --etcd-client-urls ${SENSU_ETCD_CLIENT_URLS} --cluster-admin-username ${SENSU_BACKEND_CLUSTER_ADMIN_USERNAME} --cluster-admin-password ${SENSU_BACKEND_CLUSTER_ADMIN_USERNAME} --cluster-admin-api-key ${SENSU_BACKEND_CLUSTER_ADMIN_API_KEY} --ignore-already-initialized
+    if [ $? -eq 0 ]; then
+      echo "Successfully initialized the Sensu backend!"
+      echo ""
+      return 0
+    else
+      echo "Failed to initialize the Sensu backend!"
+      echo ""
       return 1
     fi
   fi
-  return 0
 }
 
 wait_for_sensu_backend() {
