temporarily disable demo app discovery

diff --git a/scripts/workshop-auto-discovery b/scripts/workshop-auto-discovery
--- a/scripts/workshop-auto-discovery
+++ b/scripts/workshop-auto-discovery
@@ -7,6 +7,7 @@ discover_apps() {
   WORKSHOP_NETWORK=$(docker network ls --filter name=workshop_default --format "{{ .ID }}")
   WORKSHOP_APPS=$(docker ps -a --filter network=${WORKSHOP_NETWORK} --filter label="sensu.io/workshop/role=app" --format "{{ .Names }}")
   for APP in ${WORKSHOP_APPS}; do
+    # TODO: for N in namespaces?
     curl -X POST \
         -H "Authorization: Key ${SENSU_API_KEY}" \
         -H "Content-Type: application/json" \
@@ -32,12 +33,12 @@ discover_apps() {
 }
 
 echo "Auto-discovering workshop entities..."
-discover_apps
-if [ $? -gt 0 ]; then
-  echo "ERROR: failed to auto-discover workshop entities."
-  echo ""
-  exit 2
-fi
+# discover_apps
+# if [ $? -gt 0 ]; then
+#   echo "ERROR: failed to auto-discover workshop entities."
+#   echo ""
+#   exit 2
+# fi
 echo "Success!"
 echo ""
 exit 0
